version: '3.3'

services:
  web:
    image: nginx:latest
    container_name: web
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./packages/client/build:/usr/share/nginx/html

  server:
    build:
      context: ./packages/server
    container_name: server
    restart: "on-failure"
    expose:
      - 8080
    volumes:
      - './packages/server:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
